version: '3.8'

services:
  anime-upscaler-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: anime-upscaler-api-cpu
    restart: unless-stopped
    ports:
      - "${PORT:-3005}:${PORT:-3005}"  # 使用环境变量，默认3005
    volumes:
      # 数据持久化
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./Real-ESRGAN/weights:/app/Real-ESRGAN/weights
      # 配置文件挂载
      - ./config.env:/app/config.env:ro
    env_file:
      - config.env  # 加载config.env作为环境变量源
    environment:
      # 只设置必要的覆盖，不覆盖PORT
      - HOST=0.0.0.0
      - DEBUG=false
      - GPU_ID=-1  # 禁用GPU
    networks:
      - anime-upscaler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3005}/health"]  # 动态端口
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # CPU模式启动较慢

networks:
  anime-upscaler-network:
    driver: bridge 