version: '3.8'

services:
  anime-upscaler-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: anime-upscaler-api-cpu
    restart: unless-stopped
    ports:
      - "7999:7999"
    volumes:
      # 数据持久化
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./Real-ESRGAN/weights:/app/Real-ESRGAN/weights
      # 配置文件挂载
      - ./config.env:/app/config.env:ro
    environment:
      # 可以通过环境变量覆盖配置
      - HOST=0.0.0.0
      - PORT=7999
      - DEBUG=false
      - GPU_ID=-1  # 禁用GPU
    networks:
      - anime-upscaler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # CPU模式启动较慢

networks:
  anime-upscaler-network:
    driver: bridge 