version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python-gpu
    image: anime-upscaler-api:python-gpu
    container_name: anime-upscaler-python-gpu
    ports:
      - "3005:3005"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./config.env:/app/config.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 